export default [
  {
    id: 1,
    name: 'Club Atlético Bolivar',
    crestUrl: 'https://cdn.quasar.dev/img/boy-avatar.png',
    topScorer: { name: 'Luis Cabrera', goals: 18 },
    position: 1,
    founded: 1925,
    stadium: '4',
    coach: 'Martín Pérez',
    country: 'Bolivia',
  },
  {
    id: 2,
    name: 'Real Oruro FC',
    crestUrl: 'https://cdn.quasar.dev/img/boy-avatar.png',
    topScorer: { name: 'Jorge Rojas', goals: 14 },
    position: 3,
    founded: 1947,
    stadium: '9',
    coach: 'Carolina Vázquez',
    country: 'Bolivia',
  },
  {
    id: 3,
    name: 'Deportivo La Paz',
    crestUrl: null,
    topScorer: { name: 'Marcos Ávila', goals: 12 },
    position: 5,
    founded: 1962,
    stadium: '5',
    coach: 'Diego Sandoval',
    country: 'Bolivia',
  },
  {
    id: 4,
    name: 'Universitario de Sucre',
    crestUrl: null,
    topScorer: { name: 'Samuel Ortega', goals: 16 },
    position: 2,
    founded: 1966,
    stadium: '5',
    coach: 'Paula Núñez',
    country: 'Bolivia',
  },
  {
    id: 5,
    name: 'Aurora F.C.',
    crestUrl: null,
    topScorer: { name: 'Pedro Castillo', goals: 11 },
    position: 4,
    founded: 1935,
    stadium: '5',
    coach: 'Ana Fernández',
    country: 'Bolivia',
  },
];
