export default [
  {
    id: 1,
    name: 'Diego Ramírez',
    photoUrl: 'https://cdn.quasar.dev/img/avatar1.jpg',
    number: 9,
    position: 'Delantero',
    heightCm: 178,
    weightKg: 74,
    teamId: 1,
    tournament: 'Primera división',
    stats: { goals: 12, yellowCards: 2, redCards: 0, assists: 4, mvp: 3, matches: 22 },
  },
  {
    id: 2,
    name: 'Juan Pérez',
    photoUrl: 'https://cdn.quasar.dev/img/avatar2.jpg',
    number: 10,
    position: 'Mediocampista',
    heightCm: 175,
    weightKg: 70,
    teamId: 2,
    tournament: 'Primera división',
    stats: { goals: 8, yellowCards: 4, redCards: 1, assists: 6, mvp: 2, matches: 25 },
  },
  {
    id: 3,
    name: 'Carlos Gómez',
    photoUrl: 'https://cdn.quasar.dev/img/avatar3.jpg',
    number: 3,
    position: 'Defensa',
    heightCm: 183,
    weightKg: 80,
    teamId: 1,
    tournament: 'Copa local',
    stats: { goals: 1, yellowCards: 6, redCards: 0, assists: 1, mvp: 0, matches: 20 },
  },
];
